/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safe.views;

import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author chokayg3
 */
public class Doctor_View extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_View
     */
    public Doctor_View() {
        initComponents();
    }//End of Doctor_View
    
    /**
     * A method to return a button id
     * @return 
     */
    public JButton getClose_button(){
        return close_button;
    }
    
    /**
     * 
     * @return 
     */
    public JButton getOk_button(){
        return ok_button;
    }
    
    /**
     * 
     * @return 
     */
    public String getDoctorId(){
        return doctorId.getText();
    }//End of getDoctorId
    
    /**
     * 
     * @return 
     */
    public String getDoctorFname(){
        return doctorFname.getText();
    }//End of getDoctorFname
    
    /**
     * 
     * @return 
     */
    public String getDoctorSname(){
        return doctorSname.getText();
    }//End of getDoctorSname
    
    /**
     * 
     * @return 
     */
    public String getDoctorPhone(){
        return doctorPhone.getText();
    }//End of getDoctorPhone
    
    /**
     * 
     * @return 
     */
    public String getDoctorEmail(){
        return doctorEmail.getText();
    }//End of getDoctorEmail
    
    /**
     * 
     * @return 
     */
    public String getDoctorDepartment(){
        return doctorDepartment.getSelectedItem().toString();
    }
    
    /**
     * 
     * @return 
     */
    public String getDoctorDate(){
        return ((JTextField)doctorDate.getDateEditor().getUiComponent()).getText();
    }
    
    /**
     * Method to return password text field
     * @return 
     */
    public String getPassword(){
        return Arrays.toString(doctorPassword.getPassword());
    }//End of getPassword
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorBackgroundImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        doctorImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        doctorId = new javax.swing.JTextField();
        close_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        doctorPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        doctorFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doctorSname = new javax.swing.JTextField();
        doctorPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doctorEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        doctorDepartment = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        doctorDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        ok_button = new javax.swing.JButton();

        doctorBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/newdoctor3.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Unique Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorImage.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        doctorImage.setText("PHOTO");
        doctorImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorImageActionPerformed(evt);
            }
        });
        jPanel1.add(doctorImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 160));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setText("Doctor ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, 40));
        jPanel1.add(doctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 230, 40));

        close_button.setText("x");
        jPanel1.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 40));
        jPanel1.add(doctorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 190));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Doctor Details"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorFnameActionPerformed(evt);
            }
        });
        jPanel2.add(doctorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setText("Surname");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 40));
        jPanel2.add(doctorSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 230, 40));

        doctorPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(doctorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 230, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Phone");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 40));
        jPanel2.add(doctorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 230, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setText("Deparment");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 40));

        doctorDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "Cardiology", "ENT", "Gynaecology", "Haematology", "Oncology" }));
        jPanel2.add(doctorDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 230, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel8.setText("Date Joined");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 40));

        doctorDate.setDateFormatString("yyyy-MM-dd");
        doctorDate.setMaxSelectableDate(new java.util.Date(1418346060000L));
        jPanel2.add(doctorDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 730, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ok_button.setText("Ok");
        jPanel3.add(ok_button);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 730, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doctorFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorFnameActionPerformed

    private void doctorImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorImageActionPerformed

    private void doctorPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button;
    private javax.swing.JLabel doctorBackgroundImage;
    private com.toedter.calendar.JDateChooser doctorDate;
    private javax.swing.JComboBox doctorDepartment;
    private javax.swing.JTextField doctorEmail;
    private javax.swing.JTextField doctorFname;
    private javax.swing.JTextField doctorId;
    private javax.swing.JButton doctorImage;
    private javax.swing.JPasswordField doctorPassword;
    private javax.swing.JTextField doctorPhone;
    private javax.swing.JTextField doctorSname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables
}
