/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safe.views;

import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author chokayg3
 */
public class Doctor_View extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_View
     */
    public Doctor_View() {
        initComponents();
    }//End of Doctor_View
    
    /**
     * A method to return a button id
     * @return 
     */
    public JButton getClose_button(){
        return close_button;
    }
    
    /**
     * 
     * @return 
     */
    public JButton getOk_button(){
        return ok_button;
    }
    
    /**
     * 
     * @return 
     */
    public String getDoctorId(){
        return doctorId.getText();
    }//End of getDoctorId
    
    /**
     * 
     * @return 
     */
    public String getDoctorFname(){
        return doctorFname.getText();
    }//End of getDoctorFname
    
    /**
     * 
     * @return 
     */
    public String getDoctorSname(){
        return doctorSname.getText();
    }//End of getDoctorSname
    
    /**
     * 
     * @return 
     */
    public String getDoctorPhone(){
        return doctorPhone.getText();
    }//End of getDoctorPhone
    
    /**
     * 
     * @return 
     */
    public String getDoctorEmail(){
        return doctorEmail.getText();
    }//End of getDoctorEmail
    
    /**
     * 
     * @return 
     */
    public String getDoctorDepartment(){
        return doctorDepartment.getSelectedItem().toString();
    }
    
    /**
     * 
     * @return 
     */
    public String getDoctorDate(){
        return ((JTextField)doctorDate.getDateEditor().getUiComponent()).getText();
    }
    
    /**
     * Method to return password text field
     * @return 
     */
    public String getPassword(){
        return Arrays.toString(doctorPassword.getPassword());
    }//End of getPassword
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorBackgroundImage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        close_button = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        doctorImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorPassword = new javax.swing.JPasswordField();
        doctorId = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        doctorPhone = new javax.swing.JTextField();
        doctorSname = new javax.swing.JTextField();
        doctorFname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        doctorDate = new com.toedter.calendar.JDateChooser();
        doctorDepartment = new javax.swing.JComboBox();
        doctorEmail = new javax.swing.JTextField();
        ok_button = new javax.swing.JButton();

        doctorBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/newdoctor3.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("ADD DOCTOR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 160, 20));

        close_button.setText("x");
        getContentPane().add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, 20));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Unique Details"));

        doctorImage.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        doctorImage.setText("PHOTO");
        doctorImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorImageActionPerformed(evt);
            }
        });
        jDesktopPane1.add(doctorImage);
        doctorImage.setBounds(10, 20, 230, 160);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor ID");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(380, 90, 62, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(380, 140, 64, 40);
        jDesktopPane1.add(doctorPassword);
        doctorPassword.setBounds(490, 140, 230, 40);
        jDesktopPane1.add(doctorId);
        doctorId.setBounds(490, 90, 230, 40);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 730, 190));

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Doctor Details"));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        jDesktopPane2.add(jLabel3);
        jLabel3.setBounds(10, 20, 71, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Surname");
        jDesktopPane2.add(jLabel4);
        jLabel4.setBounds(10, 70, 61, 40);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");
        jDesktopPane2.add(jLabel5);
        jLabel5.setBounds(10, 120, 43, 40);

        doctorPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPhoneActionPerformed(evt);
            }
        });
        jDesktopPane2.add(doctorPhone);
        doctorPhone.setBounds(110, 120, 230, 40);
        jDesktopPane2.add(doctorSname);
        doctorSname.setBounds(110, 70, 230, 40);

        doctorFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorFnameActionPerformed(evt);
            }
        });
        jDesktopPane2.add(doctorFname);
        doctorFname.setBounds(110, 20, 230, 40);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jDesktopPane2.add(jLabel6);
        jLabel6.setBounds(380, 20, 37, 40);

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Deparment");
        jDesktopPane2.add(jLabel7);
        jLabel7.setBounds(380, 70, 74, 40);

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date Joined");
        jDesktopPane2.add(jLabel8);
        jLabel8.setBounds(380, 120, 80, 40);

        doctorDate.setDateFormatString("yyyy-MM-dd");
        doctorDate.setMaxSelectableDate(new java.util.Date(1418346060000L));
        jDesktopPane2.add(doctorDate);
        doctorDate.setBounds(490, 120, 230, 40);

        doctorDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "Cardiology", "ENT", "Gynaecology", "Haematology", "Oncology" }));
        jDesktopPane2.add(doctorDepartment);
        doctorDepartment.setBounds(490, 70, 230, 40);
        jDesktopPane2.add(doctorEmail);
        doctorEmail.setBounds(490, 20, 230, 40);

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 730, 170));

        ok_button.setText("Ok");
        getContentPane().add(ok_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doctorFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorFnameActionPerformed

    private void doctorImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorImageActionPerformed

    private void doctorPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button;
    private javax.swing.JLabel doctorBackgroundImage;
    private com.toedter.calendar.JDateChooser doctorDate;
    private javax.swing.JComboBox doctorDepartment;
    private javax.swing.JTextField doctorEmail;
    private javax.swing.JTextField doctorFname;
    private javax.swing.JTextField doctorId;
    private javax.swing.JButton doctorImage;
    private javax.swing.JPasswordField doctorPassword;
    private javax.swing.JTextField doctorPhone;
    private javax.swing.JTextField doctorSname;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables
}
