/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safe.views;

/**
 *
 * @author chokayg3
 */
public class Doctor_View extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_View
     */
    public Doctor_View() {
        initComponents();
    }//End of Doctor_View
    
    /**
     * 
     * @return 
     */
    public String getDoctorId(){
        return doctorId.getText();
    }//End of getDoctorId
    
    /**
     * 
     * @return 
     */
    public String getDoctorFname(){
        return doctorFname.getText();
    }//End of getDoctorFname
    
    /**
     * 
     * @return 
     */
    public String getDoctorSname(){
        return doctorSname.getText();
    }//End of getDoctorSname
    
    /**
     * 
     * @return 
     */
    public String getDoctorPhone(){
        return doctorPhone.getText();
    }//End of getDoctorPhone
    
    /**
     * 
     * @return 
     */
    public String getDoctorEmail(){
        return doctorEmail.getText();
    }//End of getDoctorEmail
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        doctorImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        doctorId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        doctorFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doctorSname = new javax.swing.JTextField();
        doctorPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doctorEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        ok_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/newdoctor3.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorImage.setText("PHOTO");
        jPanel1.add(doctorImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 160));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setText("Doctor ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, 30));
        jPanel1.add(doctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 230));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorFnameActionPerformed(evt);
            }
        });
        jPanel2.add(doctorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setText("Surname");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));
        jPanel2.add(doctorSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 230, 40));
        jPanel2.add(doctorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 230, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Phone");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 40));
        jPanel2.add(doctorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 230, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setText("Deparment");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cardiology", "ENT", "Gynaecology", "Haematology", "Oncology", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 130, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel8.setText("Date Joined");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, 40));

        ok_button.setText("Ok");
        jPanel2.add(ok_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        close_button.setText("x");
        jPanel2.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 790, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doctorFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorFnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button;
    private javax.swing.JTextField doctorEmail;
    private javax.swing.JTextField doctorFname;
    private javax.swing.JTextField doctorId;
    private javax.swing.JButton doctorImage;
    private javax.swing.JTextField doctorPhone;
    private javax.swing.JTextField doctorSname;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables
}
