/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safe.views;

import javax.swing.JMenuItem;

/**
 *
 * @author chokayg3
 */
public class Main_View extends javax.swing.JFrame {

    /**
     * Creates new form Main_View
     */
    public Main_View() {
        initComponents();
    }
    
    /**
     * Method to return add patient menu item
     * @return 
     */
    public JMenuItem getAddPatient_menu(){
        return addPatient_menu;
    }//End of getAddPatient
    
    /**
     * Method to return patient table menu item
     * @return 
     */
    public JMenuItem getPatientTable_menu(){
        return patientTable_menu;
    }//End of getPatientTable_menu
    
    /**
     * Method to return add doctor menu item
     * @return 
     */
    public JMenuItem getAddDoctor_menu(){
        return addDoctor_menu;
    }//End of getAddDoctor_menu
    
    /**
     * Method to return doctor table menu item
     * @return 
     */
    public JMenuItem getDoctorTable_menu(){
        return doctorTable_menu;
    }//End of getDoctorTable_menu
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        addPatient_menu = new javax.swing.JMenuItem();
        patientTable_menu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        addDoctor_menu = new javax.swing.JMenuItem();
        doctorTable_menu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAFE HOSPITAL");

        jMenuBar1.setBorder(null);

        jMenu1.setText("Patients");

        jMenu3.setText("Add");

        addPatient_menu.setText("New Patient");
        jMenu3.add(addPatient_menu);

        jMenu1.add(jMenu3);

        patientTable_menu.setText("Table");
        jMenu1.add(patientTable_menu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Doctors");

        jMenu6.setText("Add");

        addDoctor_menu.setText("New Doctor");
        jMenu6.add(addDoctor_menu);

        jMenu2.add(jMenu6);

        doctorTable_menu.setText("Table");
        jMenu2.add(doctorTable_menu);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Pharmacist");

        jMenu7.setText("jMenu7");
        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("DocPham");
        jMenuBar1.add(jMenu5);

        jMenu8.setText("Logout");
        jMenuBar1.add(jMenu8);

        jMenu9.setText("Login");
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1353, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addDoctor_menu;
    private javax.swing.JMenuItem addPatient_menu;
    private javax.swing.JMenuItem doctorTable_menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem patientTable_menu;
    // End of variables declaration//GEN-END:variables
}
