/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safe.views;

import javax.swing.JButton;
import javax.swing.JMenuItem;

/**
 *
 * @author Abayie Fredrick
 * @version 1.02
 */
public class Main_View extends javax.swing.JFrame {

    /**
     * Creates new form Main_View
     */
    public Main_View() {
        initComponents();
    }
    
    /**
     * Method to return add patient menu item
     * @return the add patient menu item
     */
    public JMenuItem getAddPatient_menu(){
        return addPatient_menu;
    }//End of getAddPatient
    
    /**
     * Method to return new doctor button
     * @return the new doctor button
     */
    public JButton getNewDoctor(){
        return newDoctor;
    }//End of getNewDoctor
    
    /**
     * Method to return new patient button
     * @return the new patient button
     */
    public JButton getNewPatient(){
        return newpatient;
    }//End of getNewPatient
    
    /**
     * Method to return patient table menu item
     * @return the patient table menu item
     */
    public JMenuItem getPatientTable_menu(){
        return patientTable_menu;
    }//End of getPatientTable_menu
    
    /**
     * Method to return add doctor menu item
     * @return the add doctor menu item
     */
    public JMenuItem getAddDoctor_menu(){
        return addDoctor_menu;
    }//End of getAddDoctor_menu
    
    /**
     * Method to return doctor table menu item
     * @return the doctor table menu item
     */
    public JMenuItem getDoctorTable_menu(){
        return doctorTable_menu;
    }//End of getDoctorTable_menu
    
    /**
     * Method to return doctor table button
     * @return the doctor table button
     */
    public JButton getDoctorTable_button(){
        return doctortable_button;
    }//End of getDoctorTable_button
    
    /**
     * Method to return patient table button
     * @return the patient table button
     */
    public JButton getPatientTable_button(){
        return patienttable_button;
    }//End of getPatientTable_button
    
    /**
     * Method to return chat menu
     * @return the chat menu item
     */
    public JMenuItem getChat_menu(){
        return chat;
    }//End of getChat_menu
    
    /**
     * Method to return chat button
     * @return the chat button
     */
    public JButton getChat(){
        return chat_button;
    }//End of getchat
    
    /**
     * Method to return doctor login menu item
     * @return the doctor login menu item
     */
    public JMenuItem getDoctorLogin_menu(){
        return doctorLogin_menu;
    }//End of getDoctorLogin_menu
    
    /**
     * Method to return how to use software pdf
     * @return the usepdf menu item
     */
    public JMenuItem getUsepdf(){
        return usepdf;
    }//End of getUsepdf
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        newpatient = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        patienttable_button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        newDoctor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        doctortable_button = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        chat_button = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        addPatient_menu = new javax.swing.JMenuItem();
        patientTable_menu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        addDoctor_menu = new javax.swing.JMenuItem();
        doctorTable_menu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        chat = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        JMenu5 = new javax.swing.JMenu();
        doctorLogin_menu = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        shortcut = new javax.swing.JMenuItem();
        usepdf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAFE HOSPITAL");

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        newpatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/add_user-48.png"))); // NOI18N
        newpatient.setToolTipText("add new patient");
        newpatient.setFocusable(false);
        newpatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newpatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newpatient);

        jLabel4.setText("        ");
        jToolBar1.add(jLabel4);

        patienttable_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/list-48.png"))); // NOI18N
        patienttable_button.setFocusable(false);
        patienttable_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        patienttable_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(patienttable_button);
        jToolBar1.add(jSeparator2);

        newDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/doctor-48.png"))); // NOI18N
        newDoctor.setToolTipText("add new doctor");
        newDoctor.setFocusable(false);
        newDoctor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newDoctor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newDoctor);

        jLabel5.setText("        ");
        jToolBar1.add(jLabel5);

        doctortable_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/View_Details-48.png"))); // NOI18N
        doctortable_button.setFocusable(false);
        doctortable_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doctortable_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(doctortable_button);
        jToolBar1.add(jSeparator3);

        chat_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/chat-48.png"))); // NOI18N
        chat_button.setFocusable(false);
        chat_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chat_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chat_button);
        jToolBar1.add(jSeparator4);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1362, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        jMenu1.setText("Patients");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/plus-26.png"))); // NOI18N
        jMenu3.setText("Add");
        jMenu3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        addPatient_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        addPatient_menu.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        addPatient_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/add_user-26.png"))); // NOI18N
        addPatient_menu.setText("New Patient");
        jMenu3.add(addPatient_menu);

        jMenu1.add(jMenu3);

        patientTable_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        patientTable_menu.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        patientTable_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/list-26.png"))); // NOI18N
        patientTable_menu.setText("Table");
        jMenu1.add(patientTable_menu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Doctors");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/plus-26.png"))); // NOI18N
        jMenu6.setText("Add");
        jMenu6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        addDoctor_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        addDoctor_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/doctor-26.png"))); // NOI18N
        addDoctor_menu.setText("New Doctor");
        jMenu6.add(addDoctor_menu);

        jMenu2.add(jMenu6);

        doctorTable_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        doctorTable_menu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        doctorTable_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/View_Details-26.png"))); // NOI18N
        doctorTable_menu.setText("Table");
        jMenu2.add(doctorTable_menu);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("DocPham");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        chat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safe/images/chat-26.png"))); // NOI18N
        chat.setText("Chat");
        jMenu5.add(chat);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Logout");
        jMenu8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu8);

        JMenu5.setText("Login");
        JMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        doctorLogin_menu.setText("Login");
        JMenu5.add(doctorLogin_menu);

        jMenuBar1.add(JMenu5);

        jMenu9.setText("Help");
        jMenu9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        shortcut.setText("Shortcuts");
        jMenu9.add(shortcut);

        usepdf.setText("How To USe");
        jMenu9.add(usepdf);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu5;
    private javax.swing.JMenuItem addDoctor_menu;
    private javax.swing.JMenuItem addPatient_menu;
    private javax.swing.JMenuItem chat;
    private javax.swing.JButton chat_button;
    private javax.swing.JMenuItem doctorLogin_menu;
    private javax.swing.JMenuItem doctorTable_menu;
    private javax.swing.JButton doctortable_button;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newDoctor;
    private javax.swing.JButton newpatient;
    private javax.swing.JMenuItem patientTable_menu;
    private javax.swing.JButton patienttable_button;
    private javax.swing.JMenuItem shortcut;
    private javax.swing.JMenuItem usepdf;
    // End of variables declaration//GEN-END:variables
}
